/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package vistas;

import inmobiliaria.Casa;
import inmobiliaria.Departamento;
import inmobiliaria.Propiedad;

/**
 *
 * @author Artemidore
 */
public class JFrameInmobiliaria extends javax.swing.JFrame {
    
    /**
     * Creates new form JFrameInmobiliaria
     */
    public JFrameInmobiliaria() {
        
        initComponents();
        CheckGaraje.setEnabled(false);
       chekExpensas.setEnabled(false);
       lblPrueba.setEnabled(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoUsos = new javax.swing.ButtonGroup();
        GrupoTipo = new javax.swing.ButtonGroup();
        JpanelPropiedad = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCantidadHabitaciones = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCantidadInquilinos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioBase = new javax.swing.JTextField();
        rbComercial = new javax.swing.JRadioButton();
        rbPrivado = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rboCasa = new javax.swing.JRadioButton();
        rboDepartamento = new javax.swing.JRadioButton();
        CheckGaraje = new javax.swing.JCheckBox();
        txtMontoExpensas = new javax.swing.JTextField();
        chekExpensas = new javax.swing.JCheckBox();
        lblPrueba = new javax.swing.JLabel();
        bttLimpiar = new javax.swing.JButton();
        bttRespuestas = new javax.swing.JButton();
        BttCargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inmobiliaria");

        JpanelPropiedad.setBorder(javax.swing.BorderFactory.createTitledBorder("Propiedad"));

        jLabel1.setText("Dirección:");

        jLabel2.setText("Cantidad habitaciones:");

        jLabel3.setText("Cantidad inquilinos:");

        jLabel4.setText("Precio base:");

        GrupoUsos.add(rbComercial);
        rbComercial.setText("Comercial");

        GrupoUsos.add(rbPrivado);
        rbPrivado.setText("Privado");

        jLabel5.setText("Uso:");

        jLabel6.setText("Tipo:");

        GrupoTipo.add(rboCasa);
        rboCasa.setText("Casa");
        rboCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboCasaActionPerformed(evt);
            }
        });

        GrupoTipo.add(rboDepartamento);
        rboDepartamento.setText("Departamento");
        rboDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboDepartamentoActionPerformed(evt);
            }
        });

        CheckGaraje.setText("Garaje");
        CheckGaraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckGarajeActionPerformed(evt);
            }
        });

        txtMontoExpensas.setText("monto");

        chekExpensas.setText("Expensas");

        lblPrueba.setText("jLabel8");

        javax.swing.GroupLayout JpanelPropiedadLayout = new javax.swing.GroupLayout(JpanelPropiedad);
        JpanelPropiedad.setLayout(JpanelPropiedadLayout);
        JpanelPropiedadLayout.setHorizontalGroup(
            JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelPropiedadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JpanelPropiedadLayout.createSequentialGroup()
                        .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelPropiedadLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccion))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelPropiedadLayout.createSequentialGroup()
                                .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(JpanelPropiedadLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCantidadHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JpanelPropiedadLayout.createSequentialGroup()
                                            .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblPrueba)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(JpanelPropiedadLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(92, 92, 92)
                                        .addComponent(rbComercial)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbPrivado)
                                    .addGroup(JpanelPropiedadLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCantidadInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rboDepartamento)
                                    .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtMontoExpensas, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chekExpensas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(JpanelPropiedadLayout.createSequentialGroup()
                        .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(90, 90, 90)
                        .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelPropiedadLayout.createSequentialGroup()
                                .addComponent(rboCasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(JpanelPropiedadLayout.createSequentialGroup()
                                .addComponent(CheckGaraje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(80, 80, 80))))
        );
        JpanelPropiedadLayout.setVerticalGroup(
            JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelPropiedadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCantidadHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantidadInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbComercial)
                    .addComponent(rbPrivado)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelPropiedadLayout.createSequentialGroup()
                        .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rboCasa)
                            .addComponent(rboDepartamento))
                        .addGap(9, 9, 9)
                        .addGroup(JpanelPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckGaraje)
                            .addComponent(chekExpensas)))
                    .addGroup(JpanelPropiedadLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMontoExpensas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrueba)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        bttLimpiar.setText("LIMPIAR");

        bttRespuestas.setText("RESPUESTAS");

        BttCargar.setText("CARGAR");
        BttCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(JpanelPropiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BttCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(bttLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttRespuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpanelPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BttCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttRespuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckGarajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckGarajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckGarajeActionPerformed

    
    
   
    private void BttCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttCargarActionPerformed
        String direccion= txtDireccion.getText();
        int cantidadHabitaciones= Integer.parseInt(txtCantidadHabitaciones.getText());
        int cantidadInquilinos= Integer.parseInt(txtCantidadInquilinos.getText());
        float precioBase= Float.parseFloat(txtPrecioBase.getText());
        boolean comercial;
        if(rbComercial.isSelected()!=true){comercial=false;}
        else{
            comercial=true;
        }
        
       
        
    }//GEN-LAST:event_BttCargarActionPerformed

    private void rboCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboCasaActionPerformed
        CheckGaraje.setEnabled(true);
        chekExpensas.setEnabled(false);
        txtMontoExpensas.setEnabled(false);
    }//GEN-LAST:event_rboCasaActionPerformed

    private void rboDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboDepartamentoActionPerformed
        CheckGaraje.setEnabled(false);
        chekExpensas.setEnabled(true);
        txtMontoExpensas.setEnabled(true);
    }//GEN-LAST:event_rboDepartamentoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInmobiliaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttCargar;
    private javax.swing.JCheckBox CheckGaraje;
    private javax.swing.ButtonGroup GrupoTipo;
    private javax.swing.ButtonGroup GrupoUsos;
    private javax.swing.JPanel JpanelPropiedad;
    private javax.swing.JButton bttLimpiar;
    private javax.swing.JButton bttRespuestas;
    private javax.swing.JCheckBox chekExpensas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblPrueba;
    private javax.swing.JRadioButton rbComercial;
    private javax.swing.JRadioButton rbPrivado;
    private javax.swing.JRadioButton rboCasa;
    private javax.swing.JRadioButton rboDepartamento;
    private javax.swing.JTextField txtCantidadHabitaciones;
    private javax.swing.JTextField txtCantidadInquilinos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMontoExpensas;
    private javax.swing.JTextField txtPrecioBase;
    // End of variables declaration//GEN-END:variables
}
